### PR TITLE
Create folders to serve full websites from

### PR DESCRIPTION
**Pull request by taylormolina7**
The project has been modified to allow the creation of "folders" which are associated with Endpoint. Any file contained in the folder can be fetched/requested as long as it is withing the actual directory associated with the Endpoint. None of this should interfere with or change the already established functionality of pages although this should be tested by someone who knows more than me about how Pages works. Some error occurred with files being served with the wrong mimeType so I also included code for detecting the file's type and ensuring that it is sent off with a corresponding mime type. There is one detail that may need attention... the requested files have to be associated with the Endpoint/folder. In other words instead of just requesting  ( /myStyles.css ) the page must request ( myCoolApp/myStyles.css ) where "/myCoolApp" is the Endpoint.

### CODE REVIEW

**Comment by TravisA9** [comment]
Sorry, I thought I issued a pull request earlier today but now see that I did not get that finished. I was pretty busy/distracted. 

Also, my son was in his github account (taylormolina7) or something and the pull request strangely switched to his name but that's me.

Please let me know if there are any problems with these changes or you have any recommendations for improvements.

**Comment by EricForgy** [comment]
Hi @TravisA9 👋 

Thanks for the PR 👍 

I am not sure about this implementation though 🤔 

This is a fairly drastic change. I had in mind something like creating a class `Public` that would handle things without changing server.jl or `Endpoint`. 

I'll put some thought into it.

PS: I am in Bangkok, so keep time differences in mind 😅

**Comment by TravisA9** [comment]
Thanks @EricForgy, for taking the time out to work on a solution for this. I hope you enjoy your time in Bangkok. 

I am still looking at the changes you made. I do have a question about it though. With these changes can I still get the websockets connection? I noticed that `sessions::Dict{Int,WebSocket}` was omitted from the Public class definition does that mean that I would have to choose between an Endpoint and just serving web pages. The reason I ask is that the project I'm working on right now requires both.

I'm sure you're busy so thanks again for your time!

**Comment by EricForgy** [comment]
Hmm...

I should confess I am not crazy about public folders. I see them as a potential security threat 🤔 

I'm not sure it is a good idea to allow a client to access an arbitrary file in a public folder that connects via websockets.

I noticed you put pages.js into a public folder in your PR, but I don't think that is necessary. Pages.jl already creates an endpoint for pages.js and that should be sufficient.

Endpoints take precedence over public folders, so if you have a file you want to serve that connects via websocket, I would suggest just creating an Endpoint for that.

If you explain your use case in more detail, I can put some thought into it. Maybe I am missing something important. What are you trying to do that can't be accomplished with the latest push?

**Comment by TravisA9** [comment]
Much like a traditional web site, the experimental project I'm working on loads any of a set of html pages which in turn load some JavaScript and css. On the other hand the project is much like a web App (at least by my definition of an App) in the sense that it stays connected to the server and constantly exchanges information which the server. 

So, of course one option would be to make a very large number of endpoints ...and in theory that would work but it does't seem practical because every time a new page, script, style sheet, image etc. is added to the project a corresponding Endpoint would also have to be made.

*Regarding the pages.js file I would probably agree... since it is really part of Pages it should probably be served by Pages and would therefore deserve its own Endpoint. It should not be in the public folder where I put it.  


> I'm not sure it is a good idea to allow a client to access an arbitrary file in a public folder that connects via websockets.

The idea here is not that a user be rummaging around in the file directory of the server but rather that a folder exist (as is traditionally done) that only contains files that the user should see. However, it should be noted that I am a far cry from a security expert so I could be overlooking some risk in the particular implementation.

Anyway, there are, of course, some great julia packages for web pages and on the other hand I could just serve web pages with about ten lines of julia code too but Pages has the more important functionality that I am interested in and need and I really like the way it's set up. 

It's difficult to predict how future users will apply anything that is built. So, really, what you decide to do depends more on them than on me. If you think that my use case will be a minority and does not fit into what you envision Pages being then I should probably do something different. One option (if you are not opposed) would be to just keep the fork and change the name. The other option would be to polish what I already had written before I discovered Pages.

**Comment by EricForgy** [comment]
I started to write a long reply, but I understand what you are saying now :)

I'll think about it, but this is a crazy week to top all crazy weeks :) Should have some time next week though.

**Comment by TravisA9** [comment]
Don't feel pressured. I really do appreciate the time you have taken out for this. I have other things to work on too so I will switch to another project until you have more time. Thanks again.

**Comment by EricForgy** [comment]
Hi @TravisA9 👋 

Since we discussed this, some great progress has been made with HTTP.jl. IN fact, this package now uses HTTP.jl, but I am still using my own router.

HTTP.jl has a built in router that does pretty much everything you want, so my plan is to keep this package the way it is. In that case, I'll go ahead and close this.  I suggest having a look at HTTP.jl though 😊

**Comment by TravisA9** [comment]
Ok, great! I look forward to testing it out. Thanks for the update @EricForgy. :+1:

**Pull request closed without merging**
